version: '3.9'
services:
  twift:
    build:
      context: ./dev
      dockerfile: Dockerfile
    image: twift
    container_name: twift
    stdin_open: true
    tty: true
    volumes:
      - ./dev/src:/twift/src:rw
    ports:
      - "5062:5062"

  twiftdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: twiftdb
    container_name: twiftdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Tokyo
      - LANG=C.UTF-8
    ports:
      - "5432:5432"

volumes:
  db_data: